SET NAMES utf8;

ALTER TABLE `tableSE3` ADD COLUMN IF NOT EXISTS `NC` int(3) DEFAULT NULL AFTER `get_data`;
ALTER TABLE `tableSE3` ADD COLUMN IF NOT EXISTS `adjustedNC` int(3) DEFAULT NULL AFTER `get_data`;
ALTER TABLE `tableSE3` ADD COLUMN IF NOT EXISTS `SessID` int(3) DEFAULT NULL AFTER `get_data`;
ALTER TABLE `tableSE3` ADD COLUMN IF NOT EXISTS `condition` int(3) DEFAULT NULL AFTER `get_data`;
ALTER TABLE `tableSE3` ADD COLUMN IF NOT EXISTS `PartID` int(3) DEFAULT NULL AFTER `get_data`;
ALTER TABLE `tableSE3` ADD COLUMN IF NOT EXISTS `response` text DEFAULT NULL AFTER `get_data`;
ALTER TABLE `tableSE3` ADD COLUMN IF NOT EXISTS `pointsTotal` int(4) DEFAULT NULL AFTER `get_data`;
ALTER TABLE `tableSE3` ADD COLUMN IF NOT EXISTS `exCorrect` int(4) DEFAULT NULL AFTER `get_data`;
ALTER TABLE `tableSE3` ADD COLUMN IF NOT EXISTS `euro_rew` FLOAT DEFAULT NULL AFTER `get_data`;
