stages:
  - base docker image
  - dev docker image
  - prod docker image
  - deploy staging

variables:
  CONTAINER_BASE_IMAGE: $CI_REGISTRY_IMAGE/app-base:$CI_COMMIT_REF_NAME
  CONTAINER_DEV_IMAGE:  $CI_REGISTRY_IMAGE/app-dev:$CI_COMMIT_REF_NAME
  CONTAINER_PROD_IMAGE: $CI_REGISTRY_IMAGE/app-prod:$CI_COMMIT_REF_NAME

build and push base image:
  stage: base docker image
  image: docker:stable
  tags:
    - icm-gitlab-runner-docker
  script:
    - echo $CI_COMMIT_REF_NAME
    - echo $CONTAINER_BASE_IMAGE
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -f docker/app/base/Dockerfile -t $CONTAINER_BASE_IMAGE .
    - docker push $CONTAINER_BASE_IMAGE
  rules:
    - changes:
      - docker/app/base/*
      when: always

build and push dev image:
  stage: dev docker image
  image: docker:stable
  tags:
    - icm-gitlab-runner-docker
  script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -f docker/app/dev/Dockerfile --build-arg image_tag=$CI_COMMIT_REF_NAME -t $CONTAINER_DEV_IMAGE .
    - docker push $CONTAINER_DEV_IMAGE
  rules:
    - changes:
        - docker/app/base/*
        - docker/app/dev/*
      when: on_success

build and push prod image:
  stage: prod docker image
  image: docker:stable
  tags:
    - icm-gitlab-runner-docker
  script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --no-cache -f docker/app/prod/Dockerfile --build-arg image_tag=$CI_COMMIT_REF_NAME --build-arg MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD --build-arg BACK_OFFICE_PASSWORD=$BACK_OFFICE_PASSWORD -t $CONTAINER_PROD_IMAGE .
    - docker push $CONTAINER_PROD_IMAGE
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "production" || $CI_COMMIT_TAG'

deploy staging:
  stage: deploy staging
  variables:
    APP_NAME: $CI_PROJECT_NAME
    ENVIRONMENT: staging
    REF_NAME: develop
    TARGET_AWS_ACCOUNT: $AWS_ACCOUNT_DEV
    VAULT_ENV_ROLE: assume-role-dev
    SKIP_TERRAFORM_PROCESS: "true"
    TF_DOCKER_VERSION: "0.15.0"
  trigger:
    project: icm-institute/dsi/dev/software-factory/deployer
    branch: cogmood
    strategy: depend
  rules:
    - if: '$CI_COMMIT_REF_NAME == "develop"'
      when: on_success
