version: '3'

services:
  mariadb-docker:
    image: mariadb:10.4.12-bionic
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./sql:/docker-entrypoint-initdb.d # excute all SQL files in this folder
      - ./migration:/migration
    expose:
      - 3306

  app:
    image: $REGISTRY_IMAGE/app-prod:${REF_NAME}
    depends_on:
      - mariadb-docker
    ports:
      - $PHP_DOCKER_PORT:80
    expose:
      - 80
    stdin_open: true
    tty: true
