version: "3.7"
services:
  php-docker:
    build: ./docker
    depends_on:
      - mariadb-docker
    environment:
      XDEBUG_CONFIG: remote_host=172.17.1.100 remote_port=9000 remote_enable=1 # todo : replace 172.17.1.100 with your docker ip
    volumes:
      - ./Emotion_Regulation_JS/:/var/www/html/
    ports: # Enable access to local browser
      - "80:80"
    stdin_open: true
    tty: true

  mariadb-docker:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 67jyt645ez5LFJIyrege456g48r
      MYSQL_DATABASE: databaseEmo
    volumes:
      - ./Emotion_Regulation_JS:/docker-entrypoint-initdb.d # excute all SQL files in this folder
    ports: # Enable access to local SQL IDE
      - "53506:3306"
    expose: # Enable access from php image
      - "3306"

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 54781:8080

  # nginx:
  #   image: nginx:mainline-alpine
  #   depends_on:
  #     - mybb
  #   logging:
  #     driver: syslog
  #     options:
  #       tag: "{{.DaemonName}}(image={{.ImageName}};name={{.Name}};id={{.ID}})"
  #   networks:
  #     - frontend
  #   ports:
  #     - '8080:80'
  #   restart: on-failure
  #   volumes:
  #     - ${PWD}/nginx:/etc/nginx/conf.d:ro
  #     - ${PWD}/mybb:/var/www/html:ro
