version: "3.7"
services:
  php-docker:
    build: ./docker
    depends_on:
      - mariadb-docker
    environment:
      XDEBUG_CONFIG: remote_host=172.17.0.1 remote_port=9000 remote_enable=1 # Replace this IP with your docker ip. Ex: ifconfig docker0.
    volumes:
      - ./src/:/var/www/html/
    ports: # Enable access to local browser
      - "$PHP_DOCKER_PORT:80"
    stdin_open: true
    tty: true

  mariadb-docker:
    image: mariadb:10.4.12-bionic
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./sql:/docker-entrypoint-initdb.d # excute all SQL files in this folder
      - /save/dumps:/tmp/dumps # Save dump
    ports: # Enable access to local SQL IDE
      - "53506:$MYSQL_INTERNAL_PORT"
    expose: # Enable access from php image
      - "$MYSQL_INTERNAL_PORT"
