function mat_conditions()
{

var test_stimuli = [
  { stimulus: "Gagner 25 euros", probabilities: 0, trial_type: 11, frame: 1, data: {test_part: 'test_gain', prob: 0.05, correct_Dummy1: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4:2 }},
  { stimulus: "Gagner 45 euros ", probabilities: 1, trial_type: 1, frame: 1, data: {test_part: 'test_gain', prob: 0.10, correct_Dummy1: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Gagner 45 euros", probabilities: 2, trial_type: 1, frame: 1, data: {test_part: 'test_gain',  prob: 0.11,correct_Dummy1: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Gagner 44 euros ", probabilities: 3, trial_type: 1, frame: 1, data: {test_part: 'test_gain', prob: 0.12, correct_Dummy1: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Gagner 43 euros", probabilities: 4, trial_type: 1, frame: 1, data: {test_part: 'test_gain',  prob: 0.13,correct_Dummy1: 2, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Gagner 43 euros ", probabilities: 5, trial_type: 1, frame: 1, data: {test_part: 'test_gain', prob: 0.14, correct_Dummy1: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Gagner 42 euros", probabilities: 6, trial_type: 1, frame: 1, data: {test_part: 'test_gain',  prob: 0.15,correct_Dummy1: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Gagner 42 euros ", probabilities: 7, trial_type: 1, frame: 1, data: {test_part: 'test_gain', prob: 0.16, correct_Dummy1:1 , correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Gagner 41 euros", probabilities: 8, trial_type: 1, frame: 1, data: {test_part: 'test_gain',  prob: 0.17,correct_Dummy1: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Gagner 41 euros ", probabilities: 9, trial_type: 1, frame: 1, data: {test_part: 'test_gain', prob: 0.18, correct_Dummy1: 2, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Gagner 40 euros", probabilities: 10, trial_type: 1, frame: 1, data: {test_part: 'test_gain', prob: 0.19, correct_Dummy1: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 1}},
  { stimulus: "Gagner 40 euros ", probabilities: 11, trial_type: 1, frame: 1, data: {test_part: 'test_gain', prob: 0.20, correct_Dummy1: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Gagner 39 euros", probabilities: 12, trial_type: 1, frame: 1, data: {test_part: 'test_gain', prob: 0.21, correct_Dummy1: 2, correct_Dummy2:2,correct_Dummy3:2,correct_Dummy4: 2}},
  { stimulus: "Gagner 39 euros ", probabilities: 13, trial_type: 1, frame: 1, data: {test_part: 'test_gain', prob: 0.22, correct_Dummy1: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Gagner 38 euros", probabilities: 14, trial_type: 1, frame: 1, data: {test_part: 'test_gain', prob: 0.23, correct_Dummy1: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Gagner 38 euros ", probabilities: 15, trial_type: 1, frame: 1, data: {test_part: 'test_gain', prob: 0.24, correct_Dummy1: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Gagner 37 euros", probabilities: 16, trial_type: 1, frame: 1, data: {test_part: 'test_gain', prob: 0.25, correct_Dummy1: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Gagner 37 euros ", probabilities: 17, trial_type: 1, frame: 1, data: {test_part: 'test_gain', prob: 0.26, correct_Dummy1: 2, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Gagner 36 euros", probabilities: 18, trial_type: 1, frame: 1, data: {test_part: 'test_gain',  prob: 0.27,correct_Dummy1: 1, correct_Dummy2:2,correct_Dummy3:2,correct_Dummy4: 2}},
  { stimulus: "Gagner 36 euros ", probabilities: 19, trial_type: 1, frame: 1, data: {test_part: 'test_gain', prob: 0.28, correct_Dummy1: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Gagner 35 euros", probabilities: 20, trial_type: 1, frame: 1, data: {test_part: 'test_gain',  prob: 0.29,correct_Dummy1: 2, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Gagner 35 euros ", probabilities: 21, trial_type: 2, frame: 1, data:{test_part: 'test_gain',  prob: 0.30,correct_Dummy1: 2, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Gagner 34 euros", probabilities: 22, trial_type: 2, frame: 1, data:{test_part: 'test_gain',  prob: 0.31,correct_Dummy1: 1, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Gagner 34 euros ", probabilities: 23, trial_type: 2, frame: 1, data:{test_part: 'test_gain', prob: 0.32, correct_Dummy1: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 1}},
  { stimulus: "Gagner 33 euros", probabilities: 24, trial_type: 2, frame: 1, data:{test_part: 'test_gain',  prob: 0.33,correct_Dummy1: 2, correct_Dummy2:2,correct_Dummy3:2,correct_Dummy4: 2}},
  { stimulus: "Gagner 33 euros ", probabilities: 25, trial_type: 2, frame: 1, data:{test_part: 'test_gain', prob: 0.34, correct_Dummy1: 2, correct_Dummy2:2,correct_Dummy3:2,correct_Dummy4: 2}},
  { stimulus: "Gagner 32 euros", probabilities: 26, trial_type: 2, frame: 1, data:{test_part: 'test_gain',  prob: 0.35,correct_Dummy1: 2, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Gagner 32 euros ", probabilities: 27, trial_type: 2, frame: 1, data:{test_part: 'test_gain', prob: 0.36, correct_Dummy1: 2, correct_Dummy2:2,correct_Dummy3:2,correct_Dummy4: 2}},
  { stimulus: "Gagner 31 euros", probabilities: 28, trial_type: 2, frame: 1, data:{test_part: 'test_gain',  prob: 0.37,correct_Dummy1: 2, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Gagner 31 euros ", probabilities: 29, trial_type: 2, frame: 1, data:{test_part: 'test_gain', prob: 0.38, correct_Dummy1: 2, correct_Dummy2:2,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Gagner 30 euros", probabilities: 30, trial_type: 2, frame: 1, data:{test_part: 'test_gain',  prob: 0.39,correct_Dummy1: 2, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Gagner 30 euros ", probabilities: 31, trial_type: 2, frame: 1, data:{test_part: 'test_gain', prob: 0.40, correct_Dummy1: 2, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Gagner 29 euros", probabilities: 32, trial_type: 2, frame: 1, data:{test_part: 'test_gain',  prob: 0.41,correct_Dummy1: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 1}},
  { stimulus: "Gagner 29 euros ", probabilities: 33, trial_type: 2, frame: 1, data:{test_part: 'test_gain', prob: 0.42, correct_Dummy1: 2, correct_Dummy2:2,correct_Dummy3:2,correct_Dummy4: 2}},
  { stimulus: "Gagner 28 euros", probabilities: 34, trial_type: 2, frame: 1, data:{test_part: 'test_gain',  prob: 0.43,correct_Dummy1: 2, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Gagner 28 euros ", probabilities: 35, trial_type: 2, frame: 1, data:{test_part: 'test_gain', prob: 0.44, correct_Dummy1: 2, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Gagner 27 euros", probabilities: 36, trial_type: 2, frame: 1, data:{test_part: 'test_gain',  prob: 0.45,correct_Dummy1: 2, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4:1}},
  { stimulus: "Gagner 27 euros ", probabilities: 37, trial_type: 2, frame: 1, data:{test_part: 'test_gain', prob: 0.46, correct_Dummy1: 2, correct_Dummy2:2,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Gagner 26 euros", probabilities: 38, trial_type: 2, frame: 1, data:{test_part: 'test_gain',  prob: 0.47,correct_Dummy1: 2, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 1}},
  { stimulus: "Gagner 26 euros ", probabilities: 39, trial_type: 2, frame: 1, data:{test_part: 'test_gain', prob: 0.48, correct_Dummy1: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 2}},
  { stimulus: "Gagner 25 euros", probabilities: 40, trial_type: 2, frame: 1, data:{test_part: 'test_gain',  prob: 0.49,correct_Dummy1: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 1}},
  { stimulus: "Gagner 25 euros ", probabilities: 41, trial_type: 3, frame: 1, data:{test_part: 'test_gain', prob: 0.50, correct_Dummy1: 2, correct_Dummy2:2,correct_Dummy3:2,correct_Dummy4: 2}},
  { stimulus: "Gagner 24 euros", probabilities: 42, trial_type: 3, frame: 1, data:{test_part: 'test_gain',  prob: 0.51,correct_Dummy1: 2, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 1}},
  { stimulus: "Gagner 24 euros ", probabilities: 43, trial_type: 3, frame: 1, data:{test_part: 'test_gain', prob: 0.52, correct_Dummy1: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 2}},
  { stimulus: "Gagner 23 euros", probabilities: 44, trial_type: 3, frame: 1, data:{test_part: 'test_gain',  prob: 0.53,correct_Dummy1: 2, correct_Dummy2:2,correct_Dummy3:2,correct_Dummy4: 2}},
  { stimulus: "Gagner 23 euros ", probabilities: 45, trial_type: 3, frame: 1, data:{test_part: 'test_gain', prob: 0.54, correct_Dummy1: 2, correct_Dummy2:2,correct_Dummy3:2,correct_Dummy4: 2}},
  { stimulus: "Gagner 22 euros", probabilities: 46, trial_type: 3, frame: 1, data:{test_part: 'test_gain',  prob: 0.55,correct_Dummy1: 2, correct_Dummy2:2,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Gagner 22 euros ", probabilities: 47, trial_type: 3, frame: 1, data:{test_part: 'test_gain', prob: 0.56, correct_Dummy1: 2, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Gagner 21 euros", probabilities: 48, trial_type: 3, frame: 1, data:{test_part: 'test_gain',  prob: 0.57,correct_Dummy1: 2, correct_Dummy2:2,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Gagner 21 euros ", probabilities: 49, trial_type: 3, frame: 1, data:{test_part: 'test_gain', prob: 0.58, correct_Dummy1: 2, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 1}},
  { stimulus: "Gagner 20 euros", probabilities: 50, trial_type: 3, frame: 1, data:{test_part: 'test_gain',  prob: 0.59,correct_Dummy1: 2, correct_Dummy2:2,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Gagner 20 euros ", probabilities: 51, trial_type: 3, frame: 1, data:{test_part: 'test_gain', prob: 0.60, correct_Dummy1: 2, correct_Dummy2:2,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Gagner 19 euros", probabilities: 52, trial_type: 3, frame: 1, data:{test_part: 'test_gain',  prob: 0.61,correct_Dummy1: 2, correct_Dummy2:2,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Gagner 19 euros ", probabilities: 53, trial_type: 3, frame: 1, data:{test_part: 'test_gain', prob: 0.62, correct_Dummy1: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Gagner 18 euros", probabilities: 54, trial_type: 3, frame: 1, data:{test_part: 'test_gain',  prob: 0.63,correct_Dummy1: 2, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 1}},
  { stimulus: "Gagner 18 euros ", probabilities: 55, trial_type: 3, frame: 1, data:{test_part: 'test_gain', prob: 0.64, correct_Dummy1: 2, correct_Dummy2:2,correct_Dummy3:2,correct_Dummy4: 2}},
  { stimulus: "Gagner 17 euros", probabilities: 56, trial_type: 3, frame: 1, data:{test_part: 'test_gain',  prob: 0.65,correct_Dummy1: 1, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 1}},
  { stimulus: "Gagner 17 euros ", probabilities: 57, trial_type: 3, frame: 1, data:{test_part: 'test_gain', prob: 0.66, correct_Dummy1: 2, correct_Dummy2:2,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Gagner 16 euros", probabilities: 58, trial_type: 3, frame: 1, data:{test_part: 'test_gain',  prob: 0.67,correct_Dummy1: 2, correct_Dummy2:2,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Gagner 16 euros ", probabilities: 59, trial_type: 3, frame: 1, data:{test_part: 'test_gain', prob: 0.68, correct_Dummy1: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 1}},
  { stimulus: "Gagner 15 euros", probabilities: 60, trial_type: 3, frame: 1, data:{test_part: 'test_gain',  prob: 0.69,correct_Dummy1: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Gagner 15 euros ", probabilities: 61, trial_type: 4, frame: 1, data:{test_part: 'test_gain', prob: 0.70, correct_Dummy1: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Gagner 14 euros", probabilities: 62, trial_type: 4, frame: 1, data:{test_part: 'test_gain',  prob: 0.71,correct_Dummy1: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Gagner 14 euros ", probabilities: 63, trial_type: 4, frame: 1, data:{test_part: 'test_gain', prob: 0.72, correct_Dummy1: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Gagner 13 euros", probabilities: 64, trial_type: 4, frame: 1, data:{test_part: 'test_gain',  prob: 0.73,correct_Dummy1: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 2}},
  { stimulus: "Gagner 13 euros ", probabilities: 65, trial_type: 4, frame: 1, data:{test_part: 'test_gain', prob: 0.74, correct_Dummy1: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Gagner 12 euros", probabilities: 66, trial_type: 4, frame: 1, data:{test_part: 'test_gain',  prob: 0.75,correct_Dummy1: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Gagner 12 euros ", probabilities: 67, trial_type: 4, frame: 1, data:{test_part: 'test_gain', prob: 0.76, correct_Dummy1: 2, correct_Dummy2:2,correct_Dummy3:2,correct_Dummy4: 2}},
  { stimulus: "Gagner 12 euros", probabilities: 68, trial_type: 4, frame: 1, data:{test_part: 'test_gain',  prob: 0.77,correct_Dummy1: 2, correct_Dummy2:2,correct_Dummy3:2,correct_Dummy4: 2}},
  { stimulus: "Gagner 11 euros ", probabilities: 69, trial_type: 4, frame: 1, data:{test_part: 'test_gain', prob: 0.78, correct_Dummy1: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Gagner 11 euros", probabilities: 70, trial_type: 4, frame: 1, data:{test_part: 'test_gain',  prob: 0.79,correct_Dummy1: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Gagner 10 euros ", probabilities: 71, trial_type: 4, frame: 1, data:{test_part: 'test_gain', prob: 0.80, correct_Dummy1: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Gagner 10 euros", probabilities: 72, trial_type: 4, frame: 1, data:{test_part: 'test_gain',  prob: 0.81,correct_Dummy1: 2, correct_Dummy2:2,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Gagner 9 euros ", probabilities: 73, trial_type: 4, frame: 1, data:{test_part: 'test_gain',  prob: 0.82,correct_Dummy1: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Gagner 9 euros", probabilities: 74, trial_type: 4, frame: 1, data:{test_part: 'test_gain',  prob: 0.83,correct_Dummy1: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Gagner 8 euros ", probabilities: 75, trial_type: 4, frame: 1, data:{test_part: 'test_gain',  prob: 0.84,correct_Dummy1: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Gagner 8 euros", probabilities: 76, trial_type: 4, frame: 1, data:{test_part: 'test_gain',  prob: 0.85,correct_Dummy1: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Gagner 7 euros ", probabilities: 77, trial_type: 4, frame: 1, data:{test_part: 'test_gain',  prob: 0.86,correct_Dummy1: 2, correct_Dummy2:2,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Gagner 7 euros", probabilities: 78, trial_type: 4, frame: 1, data:{test_part: 'test_gain',  prob: 0.87,correct_Dummy1: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Gagner 6 euros ", probabilities: 79, trial_type: 4, frame: 1, data:{test_part: 'test_gain',  prob: 0.88,correct_Dummy1: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Gagner 6 euros", probabilities: 80, trial_type: 4, frame: 1, data:{test_part: 'test_gain',  prob: 0.89,correct_Dummy1: 2, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 1}},
  { stimulus: "Gagner 5 euros ", probabilities: 81, trial_type: 4, frame: 1, data:{test_part: 'test_gain', prob: 0.90, correct_Dummy1: 2, correct_Dummy2:2,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Gagner 25 euros", probabilities: 82, trial_type: 9, frame: 1, data:{test_part: 'test_gain', prob: 0.95, correct_Dummy1: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Perdre 25 euros", probabilities: 0, trial_type: 12, frame: 0, data: {test_part: 'test_loss', prob: 0.05, correct_Dummy1: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Perdre 5 euros ", probabilities: 1, trial_type: 1, frame: 0, data: {test_part: 'test_loss', prob: 0.10, correct_Dummy1: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Perdre 6 euros", probabilities: 2, trial_type: 1, frame: 0, data: {test_part: 'test_loss',  prob: 0.11,correct_Dummy1: 1, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Perdre 6 euros ", probabilities: 3, trial_type: 1, frame: 0, data: {test_part: 'test_loss', prob: 0.12, correct_Dummy1: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 2}},
  { stimulus: "Perdre 7 euros", probabilities: 4, trial_type: 1, frame: 0, data: {test_part: 'test_loss',  prob: 0.13,correct_Dummy1: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Perdre 7 euros ", probabilities: 5, trial_type: 1, frame: 0, data: {test_part: 'test_loss', prob: 0.14, correct_Dummy1: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Perdre 8 euros", probabilities: 6, trial_type: 1, frame: 0, data: {test_part: 'test_loss', prob: 0.15, correct_Dummy1: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Perdre 8 euros ", probabilities: 7, trial_type: 1, frame: 0, data: {test_part: 'test_loss', prob: 0.16, correct_Dummy1: 1, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Perdre 9 euros", probabilities: 8, trial_type: 1, frame: 0, data: {test_part: 'test_loss',  prob: 0.17,correct_Dummy1: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 1}},
  { stimulus: "Perdre 9 euros ", probabilities: 9, trial_type: 1, frame: 0, data: {test_part: 'test_loss', prob: 0.18, correct_Dummy1: 1, correct_Dummy2:2,correct_Dummy3:2,correct_Dummy4: 2}},
  { stimulus: "Perdre 10 euros", probabilities: 10, trial_type: 1, frame: 0, data: {test_part: 'test_loss', prob: 0.19, correct_Dummy1: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Perdre 10 euros ", probabilities: 11, trial_type: 1, frame: 0, data: {test_part: 'test_loss', prob: 0.20, correct_Dummy1: 1, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Perdre 11 euros", probabilities: 12, trial_type: 1, frame: 0, data: {test_part: 'test_loss', prob: 0.21, correct_Dummy1: 1, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Perdre 11 euros ", probabilities: 13, trial_type: 1, frame: 0, data: {test_part: 'test_loss', prob: 0.22, correct_Dummy1: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Perdre 12 euros", probabilities: 14, trial_type: 1, frame: 0, data: {test_part: 'test_loss',  prob: 0.23,correct_Dummy1: 2, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Perdre 12 euros ", probabilities: 15, trial_type: 1, frame: 0, data: {test_part: 'test_loss', prob: 0.24, correct_Dummy1: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 1}},
  { stimulus: "Perdre 13 euros", probabilities: 16, trial_type: 1, frame: 0, data: {test_part: 'test_loss', prob: 0.25, correct_Dummy1: 1, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Perdre 13 euros ", probabilities: 17, trial_type: 1, frame: 0, data: {test_part: 'test_loss', prob: 0.26, correct_Dummy1: 1, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Perdre 14 euros", probabilities: 18, trial_type: 1, frame: 0, data: {test_part: 'test_loss', prob: 0.27, correct_Dummy1: 1, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 1}},
  { stimulus: "Perdre 14 euros ", probabilities: 19, trial_type: 1, frame: 0, data: {test_part: 'test_loss', prob: 0.28, correct_Dummy1: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Perdre 15 euros", probabilities: 20, trial_type: 1, frame: 0, data: {test_part: 'test_loss', prob: 0.29, correct_Dummy1: 1, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Perdre 15 euros ", probabilities: 21, trial_type: 2, frame: 0, data: {test_part: 'test_loss', prob: 0.30, correct_Dummy1: 1, correct_Dummy2:2,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Perdre 16 euros", probabilities: 22, trial_type: 2, frame: 0, data: {test_part: 'test_loss',  prob: 0.31,correct_Dummy1: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Perdre 16 euros ", probabilities: 23, trial_type: 2, frame: 0, data: {test_part: 'test_loss',  prob: 0.32,correct_Dummy1: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Perdre 17 euros", probabilities: 24, trial_type: 2, frame: 0, data: {test_part: 'test_loss',  prob: 0.33,correct_Dummy1: 1, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Perdre 17 euros ", probabilities: 25, trial_type: 2, frame: 0, data: {test_part: 'test_loss',  prob: 0.34,correct_Dummy1: 1, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Perdre 18 euros", probabilities: 26, trial_type: 2, frame: 0, data: {test_part: 'test_loss', prob: 0.35, correct_Dummy1: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 1}},
  { stimulus: "Perdre 18 euros ", probabilities: 27, trial_type: 2, frame: 0, data: {test_part: 'test_loss',  prob: 0.36,correct_Dummy1: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 2}},
  { stimulus: "Perdre 19 euros", probabilities: 28, trial_type: 2, frame: 0, data: {test_part: 'test_loss',  prob: 0.37,correct_Dummy1: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 1}},
  { stimulus: "Perdre 19 euros ", probabilities: 29, trial_type: 2, frame: 0, data: {test_part: 'test_loss', prob: 0.38, correct_Dummy1: 1, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Perdre 20 euros", probabilities: 30, trial_type: 2, frame: 0, data: {test_part: 'test_loss',  prob: 0.39,correct_Dummy1: 1, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 1}},
  { stimulus: "Perdre 20 euros ", probabilities: 31, trial_type: 2, frame: 0, data: {test_part: 'test_loss', prob: 0.40, correct_Dummy1: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Perdre 21 euros", probabilities: 32, trial_type: 2, frame: 0, data: {test_part: 'test_loss',  prob: 0.41,correct_Dummy1: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 2}},
  { stimulus: "Perdre 21 euros ", probabilities: 33, trial_type: 2, frame: 0, data: {test_part: 'test_loss', prob: 0.42, correct_Dummy1: 1, correct_Dummy2:2,correct_Dummy3:2,correct_Dummy4: 2}},
  { stimulus: "Perdre 22 euros", probabilities: 34, trial_type: 2, frame: 0, data: {test_part: 'test_loss',  prob: 0.43,correct_Dummy1: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 1}},
  { stimulus: "Perdre 22 euros ", probabilities: 35, trial_type: 2, frame: 0, data: {test_part: 'test_loss', prob: 0.44, correct_Dummy1: 1, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 1}},
  { stimulus: "Perdre 23 euros", probabilities: 36, trial_type: 2, frame: 0, data: {test_part: 'test_loss',  prob: 0.45,correct_Dummy1: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 2}},
  { stimulus: "Perdre 23 euros ", probabilities: 37, trial_type: 2, frame: 0, data: {test_part: 'test_loss', prob: 0.46, correct_Dummy1: 1, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 1}},
  { stimulus: "Perdre 24 euros", probabilities: 38, trial_type: 2, frame: 0, data: {test_part: 'test_loss', prob: 0.47, correct_Dummy1: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 2}},
  { stimulus: "Perdre 24 euros ", probabilities: 39, trial_type: 2, frame: 0, data: {test_part: 'test_loss', prob: 0.48, correct_Dummy1: 1, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 1}},
  { stimulus: "Perdre 25 euros", probabilities: 40, trial_type: 2, frame: 0, data: {test_part: 'test_loss',  prob: 0.49,correct_Dummy1: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 2}},
  { stimulus: "Perdre 25 euros ", probabilities: 41, trial_type: 3, frame: 0, data: {test_part: 'test_loss', prob: 0.50, correct_Dummy1: 1, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 1}},
  { stimulus: "Perdre 26 euros", probabilities: 42, trial_type: 3, frame: 0, data: {test_part: 'test_loss', prob: 0.51, correct_Dummy1: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Perdre 26 euros ", probabilities: 43, trial_type: 3, frame: 0, data: {test_part: 'test_loss', prob: 0.52, correct_Dummy1: 1, correct_Dummy2:2,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Perdre 27 euros", probabilities: 44, trial_type: 3, frame: 0, data: {test_part: 'test_loss', prob: 0.53, correct_Dummy1: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 2}},
  { stimulus: "Perdre 27 euros ", probabilities: 45, trial_type: 3, frame: 0, data: {test_part: 'test_loss', prob: 0.54, correct_Dummy1: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Perdre 28 euros", probabilities: 46, trial_type: 3, frame: 0, data: {test_part: 'test_loss', prob: 0.55, correct_Dummy1: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 2}},
  { stimulus: "Perdre 28 euros ", probabilities: 47, trial_type: 3, frame: 0, data: {test_part: 'test_loss', prob: 0.56, correct_Dummy1: 2, correct_Dummy2:2,correct_Dummy3:2,correct_Dummy4: 2}},
  { stimulus: "Perdre 29 euros", probabilities: 48, trial_type: 3, frame: 0, data: {test_part: 'test_loss',  prob: 0.57,correct_Dummy1: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 2}},
  { stimulus: "Perdre 29 euros ", probabilities: 49, trial_type: 3, frame: 0, data: {test_part: 'test_loss',  prob: 0.58,correct_Dummy1: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Perdre 30 euros", probabilities: 50, trial_type: 3, frame: 0, data: {test_part: 'test_loss', prob: 0.59, correct_Dummy1: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Perdre 30 euros ", probabilities: 51, trial_type: 3, frame: 0, data: {test_part: 'test_loss', prob: 0.60, correct_Dummy1: 1, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 1}},
  { stimulus: "Perdre 31 euros", probabilities: 52, trial_type: 3, frame: 0, data: {test_part: 'test_loss', prob: 0.61, correct_Dummy1: 2, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 1}},
  { stimulus: "Perdre 31 euros ", probabilities: 53, trial_type: 3, frame: 0, data: {test_part: 'test_loss', prob: 0.62, correct_Dummy1: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Perdre 32 euros", probabilities: 54, trial_type: 3, frame: 0, data: {test_part: 'test_loss', prob: 0.63, correct_Dummy1: 1, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 1}},
  { stimulus: "Perdre 32 euros ", probabilities: 55, trial_type: 3, frame: 0, data: {test_part: 'test_loss', prob: 0.64, correct_Dummy1: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Perdre 33 euros", probabilities: 56, trial_type: 3, frame: 0, data: {test_part: 'test_loss', prob: 0.65, correct_Dummy1: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 2}},
  { stimulus: "Perdre 33 euros ", probabilities: 57, trial_type: 3, frame: 0, data: {test_part: 'test_loss', prob: 0.66, correct_Dummy1: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 2}},
  { stimulus: "Perdre 34 euros", probabilities: 58, trial_type: 3, frame: 0, data: {test_part: 'test_loss', prob: 0.67, correct_Dummy1: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Perdre 34 euros ", probabilities: 59, trial_type: 3, frame: 0, data: {test_part: 'test_loss', prob: 0.68, correct_Dummy1: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Perdre 35 euros", probabilities: 60, trial_type: 3, frame: 0, data: {test_part: 'test_loss', prob: 0.69, correct_Dummy1: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 2}},
  { stimulus: "Perdre 35 euros ", probabilities: 61, trial_type: 4, frame: 0, data: {test_part: 'test_loss',  prob: 0.70,correct_Dummy1: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Perdre 36 euros", probabilities: 62, trial_type: 4, frame: 0, data: {test_part: 'test_loss', prob: 0.71, correct_Dummy1: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Perdre 36 euros ", probabilities: 63, trial_type: 4, frame: 0, data: {test_part: 'test_loss', prob: 0.72, correct_Dummy1: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Perdre 37 euros", probabilities: 64, trial_type: 4, frame: 0, data: {test_part: 'test_loss', prob: 0.73, correct_Dummy1: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Perdre 37 euros ", probabilities: 65, trial_type: 4, frame: 0, data: {test_part: 'test_loss', prob: 0.74, correct_Dummy1: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Perdre 38 euros", probabilities: 66, trial_type: 4, frame: 0, data: {test_part: 'test_loss', prob: 0.75, correct_Dummy1: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Perdre 38 euros ", probabilities: 67, trial_type: 4, frame: 0, data: {test_part: 'test_loss', prob: 0.76, correct_Dummy1: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Perdre 39 euros", probabilities: 68, trial_type: 4, frame: 0, data: {test_part: 'test_loss', prob: 0.77, correct_Dummy1: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Perdre 39 euros ", probabilities: 69, trial_type: 4, frame: 0, data: {test_part: 'test_loss', prob: 0.78, correct_Dummy1: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Perdre 40 euros", probabilities: 70, trial_type: 4, frame: 0, data: {test_part: 'test_loss',  prob: 0.79,correct_Dummy1: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Perdre 40 euros ", probabilities: 71, trial_type: 4, frame: 0, data: {test_part: 'test_loss', prob: 0.80, correct_Dummy1: 2, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 2}},
  { stimulus: "Perdre 41 euros", probabilities: 72, trial_type: 4, frame: 0, data: {test_part: 'test_loss', prob: 0.81, correct_Dummy1: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Perdre 41 euros ", probabilities: 73, trial_type: 4, frame: 0, data: {test_part: 'test_loss', prob: 0.82, correct_Dummy1: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Perdre 42 euros", probabilities: 74, trial_type: 4, frame: 0, data: {test_part: 'test_loss',  prob: 0.83,correct_Dummy1: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Perdre 42 euros ", probabilities: 75, trial_type: 4, frame: 0, data: {test_part: 'test_loss', prob: 0.84, correct_Dummy1: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Perdre 43 euros", probabilities: 76, trial_type: 4, frame: 0, data: {test_part: 'test_loss',  prob: 0.85,correct_Dummy1: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Perdre 43 euros ", probabilities: 77, trial_type: 4, frame: 0, data: {test_part: 'test_loss', prob: 0.86, correct_Dummy1: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Perdre 44 euros", probabilities: 78, trial_type: 4, frame: 0, data: {test_part: 'test_loss',  prob: 0.87,correct_Dummy1: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Perdre 44 euros ", probabilities: 79, trial_type: 4, frame: 0, data: {test_part: 'test_loss', prob: 0.88, correct_Dummy1: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Perdre 45 euros", probabilities: 80, trial_type: 4, frame: 0, data: {test_part: 'test_loss', prob: 0.89, correct_Dummy1: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Perdre 45 euros ", probabilities: 81, trial_type: 4, frame: 0, data: {test_part: 'test_loss', prob: 0.90, correct_Dummy1: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  { stimulus: "Perdre 25 euros", probabilities: 82, trial_type: 10, frame: 0, data: {test_part: 'test_loss', prob: 0.95, correct_Dummy1: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}}
  ]

  return test_stimuli
} // end function
