function mat_conditions_control()
{

var test_stimuli_control = [
  { stimulus: "4 plantes sont fertiles", probabilities: 82, trial_type: 9, data: {test_part: 'test_gain', frame: 1, prob_nocontact: 0.05, correct_ecosystem: 1}},
  { stimulus: "8 plantes sont fertiles", probabilities: 81, trial_type: 4, data: {test_part: 'test_gain', frame: 1, prob_nocontact: 0.10, correct_ecosystem: 1}},
  { stimulus: "9 plantes sont fertiles", probabilities: 80, trial_type: 4, data: {test_part: 'test_gain', frame: 1,  prob_nocontact: 0.11,correct_ecosystem: 1}},
  { stimulus: "10 plantes sont fertiles ", probabilities: 79, trial_type: 4, data: {test_part: 'test_gain', frame: 1, prob_nocontact: 0.12, correct_ecosystem: 1}},
  { stimulus: "10 plantes sont fertiles", probabilities: 78, trial_type: 4, data: {test_part: 'test_gain', frame: 1,  prob_nocontact: 0.13,correct_ecosystem: 2}},
  { stimulus: "11 plantes sont fertiles ", probabilities: 77, trial_type: 4, data: {test_part: 'test_gain', frame: 1, prob_nocontact: 0.14, correct_ecosystem: 1}},
  { stimulus: "12 plantes sont fertiles", probabilities: 76, trial_type: 4, data: {test_part: 'test_gain', frame: 1,  prob_nocontact: 0.15,correct_ecosystem: 1}},
  { stimulus: "13 plantes sont fertiles ", probabilities: 75, trial_type: 4, data: {test_part: 'test_gain', frame: 1, prob_nocontact: 0.16, correct_ecosystem:1}},
  { stimulus: "14 plantes sont fertiles", probabilities: 74, trial_type: 4, data: {test_part: 'test_gain', frame: 1,  prob_nocontact: 0.17,correct_ecosystem: 1}},
  { stimulus: "14 plantes sont fertiles ", probabilities: 73, trial_type: 4, data: {test_part: 'test_gain', frame: 1, prob_nocontact: 0.18, correct_ecosystem: 2}},
  { stimulus: "15 plantes sont fertiles", probabilities: 72, trial_type: 4, data: {test_part: 'test_gain', frame: 1, prob_nocontact: 0.19, correct_ecosystem: 1}},
  { stimulus: "16 plantes sont fertiles ", probabilities: 71, trial_type: 4, data: {test_part: 'test_gain', frame: 1, prob_nocontact: 0.20, correct_ecosystem: 1}},
  { stimulus: "17 plantes sont fertiles", probabilities: 70, trial_type: 4, data: {test_part: 'test_gain', frame: 1, prob_nocontact: 0.21, correct_ecosystem: 2}},
  { stimulus: "18 plantes sont fertiles ", probabilities: 69, trial_type: 4, data: {test_part: 'test_gain', frame: 1, prob_nocontact: 0.22, correct_ecosystem: 1}},
  { stimulus: "18 plantes sont fertiles", probabilities: 68, trial_type: 4, data: {test_part: 'test_gain', frame: 1, prob_nocontact: 0.23, correct_ecosystem: 1}},
  { stimulus: "19 plantes sont fertiles ", probabilities: 67, trial_type: 4, data: {test_part: 'test_gain', frame: 1, prob_nocontact: 0.24, correct_ecosystem: 1}},
  { stimulus: "20 plantes sont fertiles", probabilities: 66, trial_type: 4, data: {test_part: 'test_gain', frame: 1, prob_nocontact: 0.25, correct_ecosystem: 1}},
  { stimulus: "21 plantes sont fertiles ", probabilities: 65, trial_type: 4, data: {test_part: 'test_gain', frame: 1, prob_nocontact: 0.26, correct_ecosystem: 2}},
  { stimulus: "22 plantes sont fertiles", probabilities: 64, trial_type: 4, data: {test_part: 'test_gain', frame: 1,  prob_nocontact: 0.27,correct_ecosystem: 1}},
  { stimulus: "22 plantes sont fertiles ", probabilities: 63, trial_type: 4, data: {test_part: 'test_gain', frame: 1, prob_nocontact: 0.28, correct_ecosystem: 1}},
  { stimulus: "23 plantes sont fertiles", probabilities: 62, trial_type: 4, data: {test_part: 'test_gain', frame: 1,  prob_nocontact: 0.29,correct_ecosystem: 2}},
  { stimulus: "24 plantes sont fertiles ", probabilities: 61, trial_type: 3, data:{test_part: 'test_gain', frame: 1,  prob_nocontact: 0.30,correct_ecosystem: 2}},
  { stimulus: "25 plantes sont fertiles", probabilities: 60, trial_type: 3, data:{test_part: 'test_gain', frame: 1,  prob_nocontact: 0.31,correct_ecosystem: 1}},
  { stimulus: "26 plantes sont fertiles ", probabilities: 59, trial_type: 3, data:{test_part: 'test_gain', frame: 1, prob_nocontact: 0.32, correct_ecosystem: 1}},
  { stimulus: "26 plantes sont fertiles", probabilities: 58, trial_type: 3, data:{test_part: 'test_gain', frame: 1,  prob_nocontact: 0.33,correct_ecosystem: 2}},
  { stimulus: "27 plantes sont fertiles ", probabilities: 57, trial_type: 3, data:{test_part: 'test_gain', frame: 1, prob_nocontact: 0.34, correct_ecosystem: 2}},
  { stimulus: "28 plantes sont fertiles", probabilities: 56, trial_type: 3, data:{test_part: 'test_gain', frame: 1,  prob_nocontact: 0.35,correct_ecosystem: 2}},
  { stimulus: "29 plantes sont fertiles ", probabilities: 55, trial_type: 3, data:{test_part: 'test_gain', frame: 1, prob_nocontact: 0.36, correct_ecosystem: 2}},
  { stimulus: "30 plantes sont fertiles", probabilities: 54, trial_type: 3, data:{test_part: 'test_gain', frame: 1,  prob_nocontact: 0.37,correct_ecosystem: 2}},
  { stimulus: "30 plantes sont fertiles ", probabilities: 53, trial_type: 3, data:{test_part: 'test_gain', frame: 1, prob_nocontact: 0.38, correct_ecosystem: 2}},
  { stimulus: "31 plantes sont fertiles", probabilities: 52, trial_type: 3, data:{test_part: 'test_gain', frame: 1,  prob_nocontact: 0.39,correct_ecosystem: 2}},
  { stimulus: "32 plantes sont fertiles ", probabilities: 51, trial_type: 3, data:{test_part: 'test_gain', frame: 1, prob_nocontact: 0.40, correct_ecosystem: 2}},
  { stimulus: "33 plantes sont fertiles", probabilities: 50, trial_type: 3, data:{test_part: 'test_gain', frame: 1,  prob_nocontact: 0.41,correct_ecosystem: 1}},
  { stimulus: "34 plantes sont fertiles ", probabilities: 49, trial_type: 3, data:{test_part: 'test_gain', frame: 1, prob_nocontact: 0.42, correct_ecosystem: 2}},
  { stimulus: "34 plantes sont fertiles", probabilities: 48, trial_type: 3, data:{test_part: 'test_gain', frame: 1,  prob_nocontact: 0.43,correct_ecosystem: 2}},
  { stimulus: "35 plantes sont fertiles ", probabilities: 47, trial_type: 3, data:{test_part: 'test_gain', frame: 1, prob_nocontact: 0.44, correct_ecosystem: 2}},
  { stimulus: "36 plantes sont fertiles", probabilities: 46, trial_type: 3, data:{test_part: 'test_gain', frame: 1,  prob_nocontact: 0.45,correct_ecosystem: 2}},
  { stimulus: "37 plantes sont fertiles ", probabilities: 45, trial_type: 3, data:{test_part: 'test_gain', frame: 1, prob_nocontact: 0.46, correct_ecosystem: 2}},
  { stimulus: "38 plantes sont fertiles", probabilities: 44, trial_type: 3, data:{test_part: 'test_gain', frame: 1,  prob_nocontact: 0.47,correct_ecosystem: 2}},
  { stimulus: "38 plantes sont fertiles ", probabilities: 43, trial_type: 3, data:{test_part: 'test_gain', frame: 1, prob_nocontact: 0.48, correct_ecosystem: 2}},
  { stimulus: "39 plantes sont fertiles", probabilities: 42, trial_type: 3, data:{test_part: 'test_gain', frame: 1,  prob_nocontact: 0.49,correct_ecosystem: 1}},
  { stimulus: "40 plantes sont fertiles ", probabilities: 41, trial_type: 2, data:{test_part: 'test_gain', frame: 1, prob_nocontact: 0.50, correct_ecosystem: 2}},
  { stimulus: "41 plantes sont fertiles", probabilities: 40, trial_type: 2, data:{test_part: 'test_gain', frame: 1,  prob_nocontact: 0.51,correct_ecosystem: 2}},
  { stimulus: "42 plantes sont fertiles ", probabilities: 39, trial_type: 2, data:{test_part: 'test_gain', frame: 1, prob_nocontact: 0.52, correct_ecosystem: 2}},
  { stimulus: "42 plantes sont fertiles", probabilities: 38, trial_type: 2, data:{test_part: 'test_gain', frame: 1,  prob_nocontact: 0.53,correct_ecosystem: 2}},
  { stimulus: "43 plantes sont fertiles ", probabilities: 37, trial_type: 2, data:{test_part: 'test_gain', frame: 1, prob_nocontact: 0.54, correct_ecosystem: 2}},
  { stimulus: "44 plantes sont fertiles", probabilities: 36, trial_type: 2, data:{test_part: 'test_gain', frame: 1,  prob_nocontact: 0.55,correct_ecosystem: 2}},
  { stimulus: "45 plantes sont fertiles ", probabilities: 35, trial_type: 2, data:{test_part: 'test_gain', frame: 1, prob_nocontact: 0.56, correct_ecosystem: 2}},
  { stimulus: "46 plantes sont fertiles", probabilities: 34, trial_type: 2, data:{test_part: 'test_gain', frame: 1,  prob_nocontact: 0.57,correct_ecosystem: 2}},
  { stimulus: "46 plantes sont fertiles ", probabilities: 33, trial_type: 2, data:{test_part: 'test_gain', frame: 1, prob_nocontact: 0.58, correct_ecosystem: 2}},
  { stimulus: "47 plantes sont fertiles", probabilities: 32, trial_type: 2, data:{test_part: 'test_gain', frame: 1,  prob_nocontact: 0.59,correct_ecosystem: 2}},
  { stimulus: "48 plantes sont fertiles ", probabilities: 31, trial_type: 2, data:{test_part: 'test_gain', frame: 1, prob_nocontact: 0.60, correct_ecosystem: 2}},
  { stimulus: "49 plantes sont fertiles", probabilities: 30, trial_type: 2, data:{test_part: 'test_gain', frame: 1,  prob_nocontact: 0.61,correct_ecosystem: 2}},
  { stimulus: "50 plantes sont fertiles ", probabilities: 29, trial_type: 2, data:{test_part: 'test_gain', frame: 1, prob_nocontact: 0.62, correct_ecosystem: 2}},
  { stimulus: "50 plantes sont fertiles", probabilities: 28, trial_type: 2, data:{test_part: 'test_gain', frame: 1,  prob_nocontact: 0.63,correct_ecosystem: 2}},
  { stimulus: "51 plantes sont fertiles ", probabilities: 27, trial_type: 2, data:{test_part: 'test_gain', frame: 1, prob_nocontact: 0.64, correct_ecosystem: 2}},
  { stimulus: "52 plantes sont fertiles", probabilities: 26, trial_type: 2, data:{test_part: 'test_gain', frame: 1,  prob_nocontact: 0.65,correct_ecosystem: 1}},
  { stimulus: "53 plantes sont fertiles ", probabilities: 25, trial_type: 2, data:{test_part: 'test_gain', frame: 1, prob_nocontact: 0.66, correct_ecosystem: 2}},
  { stimulus: "54 plantes sont fertiles", probabilities: 24, trial_type: 2, data:{test_part: 'test_gain', frame: 1,  prob_nocontact: 0.67,correct_ecosystem: 2}},
  { stimulus: "54 plantes sont fertiles ", probabilities: 23, trial_type: 2, data:{test_part: 'test_gain', frame: 1, prob_nocontact: 0.68, correct_ecosystem: 1}},
  { stimulus: "55 plantes sont fertiles", probabilities: 22, trial_type: 2, data:{test_part: 'test_gain', frame: 1,  prob_nocontact: 0.69,correct_ecosystem: 2}},
  { stimulus: "56 plantes sont fertiles ", probabilities: 21, trial_type: 1, data:{test_part: 'test_gain', frame: 1, prob_nocontact: 0.70, correct_ecosystem: 2}},
  { stimulus: "57 plantes sont fertiles", probabilities: 20, trial_type: 1, data:{test_part: 'test_gain', frame: 1,  prob_nocontact: 0.71,correct_ecosystem: 2}},
  { stimulus: "58 plantes sont fertiles ", probabilities: 19, trial_type: 1, data:{test_part: 'test_gain', frame: 1, prob_nocontact: 0.72, correct_ecosystem: 2}},
  { stimulus: "58 plantes sont fertiles", probabilities: 18, trial_type: 1, data:{test_part: 'test_gain', frame: 1,  prob_nocontact: 0.73,correct_ecosystem: 2}},
  { stimulus: "59 plantes sont fertiles ", probabilities:17, trial_type: 1, data:{test_part: 'test_gain', frame: 1, prob_nocontact: 0.74, correct_ecosystem: 2}},
  { stimulus: "60 plantes sont fertiles", probabilities: 16, trial_type: 1, data:{test_part: 'test_gain', frame: 1,  prob_nocontact: 0.75,correct_ecosystem: 2}},
  { stimulus: "61 plantes sont fertiles ", probabilities: 15, trial_type: 1, data:{test_part: 'test_gain', frame: 1, prob_nocontact: 0.76, correct_ecosystem: 2}},
  { stimulus: "62 plantes sont fertiles", probabilities: 14, trial_type: 1, data:{test_part: 'test_gain', frame: 1,  prob_nocontact: 0.77,correct_ecosystem: 2}},
  { stimulus: "62 plantes sont fertiles ", probabilities: 13, trial_type: 1, data:{test_part: 'test_gain', frame: 1, prob_nocontact: 0.78, correct_ecosystem: 2}},
  { stimulus: "63 plantes sont fertiles", probabilities: 12, trial_type: 1, data:{test_part: 'test_gain', frame: 1,  prob_nocontact: 0.79,correct_ecosystem: 2}},
  { stimulus: "64 plantes sont fertiles ", probabilities: 11, trial_type: 1, data:{test_part: 'test_gain', frame: 1, prob_nocontact: 0.80, correct_ecosystem: 2}},
  { stimulus: "65 plantes sont fertiles", probabilities: 10, trial_type: 1, data:{test_part: 'test_gain', frame: 1,  prob_nocontact: 0.81,correct_ecosystem: 2}},
  { stimulus: "66 plantes sont fertiles ", probabilities: 9, trial_type: 1, data:{test_part: 'test_gain', frame: 1,  prob_nocontact: 0.82,correct_ecosystem: 2}},
  { stimulus: "66 plantes sont fertiles", probabilities: 8, trial_type: 1, data:{test_part: 'test_gain', frame: 1,  prob_nocontact: 0.83,correct_ecosystem: 2}},
  { stimulus: "67 plantes sont fertiles ", probabilities: 7, trial_type: 1, data:{test_part: 'test_gain', frame: 1,  prob_nocontact: 0.84,correct_ecosystem: 2}},
  { stimulus: "68 plantes sont fertiles", probabilities: 6, trial_type: 1, data:{test_part: 'test_gain', frame: 1,  prob_nocontact: 0.85,correct_ecosystem: 2}},
  { stimulus: "69 plantes sont fertiles ", probabilities: 5, trial_type: 1, data:{test_part: 'test_gain', frame: 1,  prob_nocontact: 0.86,correct_ecosystem: 2}},
  { stimulus: "70 plantes sont fertiles", probabilities: 4, trial_type: 1, data:{test_part: 'test_gain', frame: 1,  prob_nocontact: 0.87,correct_ecosystem: 2}},
  { stimulus: "70 plantes sont fertiles ", probabilities: 3, trial_type: 1, data:{test_part: 'test_gain', frame: 1,  prob_nocontact: 0.88,correct_ecosystem: 2}},
  { stimulus: "71 plantes sont fertiles", probabilities: 2, trial_type: 1, data:{test_part: 'test_gain', frame: 1,  prob_nocontact: 0.89,correct_ecosystem: 2}},
  { stimulus: "72 plantes sont fertiles ", probabilities: 1, trial_type: 1, data:{test_part: 'test_gain', frame: 1, prob_nocontact: 0.90, correct_ecosystem: 2}},
  { stimulus: "76 plantes sont fertiles", probabilities: 0, trial_type: 11, data:{test_part: 'test_gain', frame: 1, prob_nocontact: 0.95, correct_ecosystem: 2}},
  // { stimulus: "Perdre 25 euros", probabilities: 0, trial_type: 12, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.05, correct_ecosystem: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  // { stimulus: "Perdre 5 euros ", probabilities: 1, trial_type: 1, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.10, correct_ecosystem: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  // { stimulus: "Perdre 6 euros", probabilities: 2, trial_type: 1, data: {test_part: 'test_loss', frame: 0,  prob_nocontact: 0.11,correct_ecosystem: 1, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 2}},
  // { stimulus: "Perdre 6 euros ", probabilities: 3, trial_type: 1, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.12, correct_ecosystem: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 2}},
  // { stimulus: "Perdre 7 euros", probabilities: 4, trial_type: 1, data: {test_part: 'test_loss', frame: 0,  prob_nocontact: 0.13,correct_ecosystem: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  // { stimulus: "Perdre 7 euros ", probabilities: 5, trial_type: 1, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.14, correct_ecosystem: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  // { stimulus: "Perdre 8 euros", probabilities: 6, trial_type: 1, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.15, correct_ecosystem: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  // { stimulus: "Perdre 8 euros ", probabilities: 7, trial_type: 1, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.16, correct_ecosystem: 1, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 2}},
  // { stimulus: "Perdre 9 euros", probabilities: 8, trial_type: 1, data: {test_part: 'test_loss', frame: 0,  prob_nocontact: 0.17,correct_ecosystem: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 1}},
  // { stimulus: "Perdre 9 euros ", probabilities: 9, trial_type: 1, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.18, correct_ecosystem: 1, correct_Dummy2:2,correct_Dummy3:2,correct_Dummy4: 2}},
  // { stimulus: "Perdre 10 euros", probabilities: 10, trial_type: 1, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.19, correct_ecosystem: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  // { stimulus: "Perdre 10 euros ", probabilities: 11, trial_type: 1, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.20, correct_ecosystem: 1, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 2}},
  // { stimulus: "Perdre 11 euros", probabilities: 12, trial_type: 1, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.21, correct_ecosystem: 1, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 2}},
  // { stimulus: "Perdre 11 euros ", probabilities: 13, trial_type: 1, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.22, correct_ecosystem: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  // { stimulus: "Perdre 12 euros", probabilities: 14, trial_type: 1, data: {test_part: 'test_loss', frame: 0,  prob_nocontact: 0.23,correct_ecosystem: 2, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 2}},
  // { stimulus: "Perdre 12 euros ", probabilities: 15, trial_type: 1, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.24, correct_ecosystem: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 1}},
  // { stimulus: "Perdre 13 euros", probabilities: 16, trial_type: 1, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.25, correct_ecosystem: 1, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 2}},
  // { stimulus: "Perdre 13 euros ", probabilities: 17, trial_type: 1, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.26, correct_ecosystem: 1, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 2}},
  // { stimulus: "Perdre 14 euros", probabilities: 18, trial_type: 1, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.27, correct_ecosystem: 1, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 1}},
  // { stimulus: "Perdre 14 euros ", probabilities: 19, trial_type: 1, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.28, correct_ecosystem: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  // { stimulus: "Perdre 15 euros", probabilities: 20, trial_type: 1, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.29, correct_ecosystem: 1, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 2}},
  // { stimulus: "Perdre 15 euros ", probabilities: 21, trial_type: 2, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.30, correct_ecosystem: 1, correct_Dummy2:2,correct_Dummy3:2,correct_Dummy4: 1}},
  // { stimulus: "Perdre 16 euros", probabilities: 22, trial_type: 2, data: {test_part: 'test_loss', frame: 0,  prob_nocontact: 0.31,correct_ecosystem: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  // { stimulus: "Perdre 16 euros ", probabilities: 23, trial_type: 2, data: {test_part: 'test_loss', frame: 0,  prob_nocontact: 0.32,correct_ecosystem: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  // { stimulus: "Perdre 17 euros", probabilities: 24, trial_type: 2, data: {test_part: 'test_loss', frame: 0,  prob_nocontact: 0.33,correct_ecosystem: 1, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 2}},
  // { stimulus: "Perdre 17 euros ", probabilities: 25, trial_type: 2, data: {test_part: 'test_loss', frame: 0,  prob_nocontact: 0.34,correct_ecosystem: 1, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 2}},
  // { stimulus: "Perdre 18 euros", probabilities: 26, trial_type: 2, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.35, correct_ecosystem: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 1}},
  // { stimulus: "Perdre 18 euros ", probabilities: 27, trial_type: 2, data: {test_part: 'test_loss', frame: 0,  prob_nocontact: 0.36,correct_ecosystem: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 2}},
  // { stimulus: "Perdre 19 euros", probabilities: 28, trial_type: 2, data: {test_part: 'test_loss', frame: 0,  prob_nocontact: 0.37,correct_ecosystem: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 1}},
  // { stimulus: "Perdre 19 euros ", probabilities: 29, trial_type: 2, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.38, correct_ecosystem: 1, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 2}},
  // { stimulus: "Perdre 20 euros", probabilities: 30, trial_type: 2, data: {test_part: 'test_loss', frame: 0,  prob_nocontact: 0.39,correct_ecosystem: 1, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 1}},
  // { stimulus: "Perdre 20 euros ", probabilities: 31, trial_type: 2, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.40, correct_ecosystem: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 2}},
  // { stimulus: "Perdre 21 euros", probabilities: 32, trial_type: 2, data: {test_part: 'test_loss', frame: 0,  prob_nocontact: 0.41,correct_ecosystem: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 2}},
  // { stimulus: "Perdre 21 euros ", probabilities: 33, trial_type: 2, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.42, correct_ecosystem: 1, correct_Dummy2:2,correct_Dummy3:2,correct_Dummy4: 2}},
  // { stimulus: "Perdre 22 euros", probabilities: 34, trial_type: 2, data: {test_part: 'test_loss', frame: 0,  prob_nocontact: 0.43,correct_ecosystem: 1, correct_Dummy2:2,correct_Dummy3:1,correct_Dummy4: 1}},
  // { stimulus: "Perdre 22 euros ", probabilities: 35, trial_type: 2, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.44, correct_ecosystem: 1, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 1}},
  // { stimulus: "Perdre 23 euros", probabilities: 36, trial_type: 2, data: {test_part: 'test_loss', frame: 0,  prob_nocontact: 0.45,correct_ecosystem: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 2}},
  // { stimulus: "Perdre 23 euros ", probabilities: 37, trial_type: 2, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.46, correct_ecosystem: 1, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 1}},
  // { stimulus: "Perdre 24 euros", probabilities: 38, trial_type: 2, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.47, correct_ecosystem: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 2}},
  // { stimulus: "Perdre 24 euros ", probabilities: 39, trial_type: 2, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.48, correct_ecosystem: 1, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 1}},
  // { stimulus: "Perdre 25 euros", probabilities: 40, trial_type: 2, data: {test_part: 'test_loss', frame: 0,  prob_nocontact: 0.49,correct_ecosystem: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 2}},
  // { stimulus: "Perdre 25 euros ", probabilities: 41, trial_type: 3, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.50, correct_ecosystem: 1, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 1}},
  // { stimulus: "Perdre 26 euros", probabilities: 42, trial_type: 3, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.51, correct_ecosystem: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  // { stimulus: "Perdre 26 euros ", probabilities: 43, trial_type: 3, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.52, correct_ecosystem: 1, correct_Dummy2:2,correct_Dummy3:2,correct_Dummy4: 1}},
  // { stimulus: "Perdre 27 euros", probabilities: 44, trial_type: 3, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.53, correct_ecosystem: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 2}},
  // { stimulus: "Perdre 27 euros ", probabilities: 45, trial_type: 3, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.54, correct_ecosystem: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  // { stimulus: "Perdre 28 euros", probabilities: 46, trial_type: 3, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.55, correct_ecosystem: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 2}},
  // { stimulus: "Perdre 28 euros ", probabilities: 47, trial_type: 3, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.56, correct_ecosystem: 2, correct_Dummy2:2,correct_Dummy3:2,correct_Dummy4: 2}},
  // { stimulus: "Perdre 29 euros", probabilities: 48, trial_type: 3, data: {test_part: 'test_loss', frame: 0,  prob_nocontact: 0.57,correct_ecosystem: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 2}},
  // { stimulus: "Perdre 29 euros ", probabilities: 49, trial_type: 3, data: {test_part: 'test_loss', frame: 0,  prob_nocontact: 0.58,correct_ecosystem: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  // { stimulus: "Perdre 30 euros", probabilities: 50, trial_type: 3, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.59, correct_ecosystem: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  // { stimulus: "Perdre 30 euros ", probabilities: 51, trial_type: 3, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.60, correct_ecosystem: 1, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 1}},
  // { stimulus: "Perdre 31 euros", probabilities: 52, trial_type: 3, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.61, correct_ecosystem: 2, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 1}},
  // { stimulus: "Perdre 31 euros ", probabilities: 53, trial_type: 3, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.62, correct_ecosystem: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  // { stimulus: "Perdre 32 euros", probabilities: 54, trial_type: 3, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.63, correct_ecosystem: 1, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 1}},
  // { stimulus: "Perdre 32 euros ", probabilities: 55, trial_type: 3, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.64, correct_ecosystem: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  // { stimulus: "Perdre 33 euros", probabilities: 56, trial_type: 3, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.65, correct_ecosystem: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 2}},
  // { stimulus: "Perdre 33 euros ", probabilities: 57, trial_type: 3, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.66, correct_ecosystem: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 2}},
  // { stimulus: "Perdre 34 euros", probabilities: 58, trial_type: 3, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.67, correct_ecosystem: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  // { stimulus: "Perdre 34 euros ", probabilities: 59, trial_type: 3, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.68, correct_ecosystem: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  // { stimulus: "Perdre 35 euros", probabilities: 60, trial_type: 3, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.69, correct_ecosystem: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 2}},
  // { stimulus: "Perdre 35 euros ", probabilities: 61, trial_type: 4, data: {test_part: 'test_loss', frame: 0,  prob_nocontact: 0.70,correct_ecosystem: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  // { stimulus: "Perdre 36 euros", probabilities: 62, trial_type: 4, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.71, correct_ecosystem: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  // { stimulus: "Perdre 36 euros ", probabilities: 63, trial_type: 4, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.72, correct_ecosystem: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  // { stimulus: "Perdre 37 euros", probabilities: 64, trial_type: 4, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.73, correct_ecosystem: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  // { stimulus: "Perdre 37 euros ", probabilities: 65, trial_type: 4, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.74, correct_ecosystem: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  // { stimulus: "Perdre 38 euros", probabilities: 66, trial_type: 4, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.75, correct_ecosystem: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  // { stimulus: "Perdre 38 euros ", probabilities: 67, trial_type: 4, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.76, correct_ecosystem: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  // { stimulus: "Perdre 39 euros", probabilities: 68, trial_type: 4, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.77, correct_ecosystem: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  // { stimulus: "Perdre 39 euros ", probabilities: 69, trial_type: 4, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.78, correct_ecosystem: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  // { stimulus: "Perdre 40 euros", probabilities: 70, trial_type: 4, data: {test_part: 'test_loss', frame: 0,  prob_nocontact: 0.79,correct_ecosystem: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  // { stimulus: "Perdre 40 euros ", probabilities: 71, trial_type: 4, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.80, correct_ecosystem: 2, correct_Dummy2:1,correct_Dummy3:1,correct_Dummy4: 2}},
  // { stimulus: "Perdre 41 euros", probabilities: 72, trial_type: 4, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.81, correct_ecosystem: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  // { stimulus: "Perdre 41 euros ", probabilities: 73, trial_type: 4, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.82, correct_ecosystem: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  // { stimulus: "Perdre 42 euros", probabilities: 74, trial_type: 4, data: {test_part: 'test_loss', frame: 0,  prob_nocontact: 0.83,correct_ecosystem: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  // { stimulus: "Perdre 42 euros ", probabilities: 75, trial_type: 4, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.84, correct_ecosystem: 1, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  // { stimulus: "Perdre 43 euros", probabilities: 76, trial_type: 4, data: {test_part: 'test_loss', frame: 0,  prob_nocontact: 0.85,correct_ecosystem: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  // { stimulus: "Perdre 43 euros ", probabilities: 77, trial_type: 4, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.86, correct_ecosystem: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  // { stimulus: "Perdre 44 euros", probabilities: 78, trial_type: 4, data: {test_part: 'test_loss', frame: 0,  prob_nocontact: 0.87,correct_ecosystem: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  // { stimulus: "Perdre 44 euros ", probabilities: 79, trial_type: 4, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.88, correct_ecosystem: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  // { stimulus: "Perdre 45 euros", probabilities: 80, trial_type: 4, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.89, correct_ecosystem: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  // { stimulus: "Perdre 45 euros ", probabilities: 81, trial_type: 4, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.90, correct_ecosystem: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}},
  // { stimulus: "Perdre 25 euros", probabilities: 82, trial_type: 10, data: {test_part: 'test_loss', frame: 0, prob_nocontact: 0.95, correct_ecosystem: 2, correct_Dummy2:1,correct_Dummy3:2,correct_Dummy4: 1}}
  ]

  return test_stimuli_control
} // end function
